name: sirroco_mobile_recruitment
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  device_preview: ^1.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
